name: Build main branch

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Change to Timestamped Version
        run: |
          startTime=$(TZ="Asia/Kolkata" date +'%Y%m%d-%H%M00')
          latestCommit=$(git log -n 1 --pretty=format:"%h")
          VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)
          updatedVersion=$VERSION-$startTime-$latestCommit
          echo $updatedVersion
          sed -i "s/version=\(.*\)/version=$updatedVersion/g" gradle.properties
      - name: Github Packages Publish
        env:
          publishUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          publishPAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: ./gradlew publish
